const FETCH_USER_QUERY_KEY = 'fetch-user';
const FETCH_ALL_USERS_QUERY_KEY = 'fetch-all-user';
const ADD_COINS_QUERY_KEY = 'add-coins';
const FETCH_SENDING_HISTORY_QUERY_KEY = 'fetch-sending-history';
const FETCH_LEADERS_QUERY_KEY = 'fetch-leaders';

export {
  FETCH_USER_QUERY_KEY,
  ADD_COINS_QUERY_KEY,
  FETCH_ALL_USERS_QUERY_KEY,
  FETCH_SENDING_HISTORY_QUERY_KEY,
  FETCH_LEADERS_QUERY_KEY
};
