const BASE_COST_MULTIPLIER = 1.5;
const MAX_OFFLINE_TIME_IN_SECONDS = 10_800;
const MAX_OFFLINE_TIME_IN_HOURS = 3;
const REFERRAL_INCOME_MULTIPLIER = 0.3;
const DEFAULT_ANIMATION_DURATION_MS = 200;
const DAY_IN_MS = 86_400_000;

export {
  BASE_COST_MULTIPLIER,
  MAX_OFFLINE_TIME_IN_SECONDS,
  MAX_OFFLINE_TIME_IN_HOURS,
  REFERRAL_INCOME_MULTIPLIER,
  DEFAULT_ANIMATION_DURATION_MS,
  DAY_IN_MS
};
