const CARD_SET_TIME_FOR_COST_SECONDS = 600 // 10 minutes
const UPGRADES_TO_OPEN_SETS = 5;
const BASE_COST_BOOST_SET = 10000;

export { CARD_SET_TIME_FOR_COST_SECONDS, UPGRADES_TO_OPEN_SETS, BASE_COST_BOOST_SET };
