const CLICK_X_OFFSET = 20;
const CLICK_Y_OFFSET = 130;
const RANDOM_CLICK_ROTATION_DEGREE = 90;
const RANDOM_OFFSET_X = 20;

export { CLICK_X_OFFSET, CLICK_Y_OFFSET, RANDOM_CLICK_ROTATION_DEGREE, RANDOM_OFFSET_X };
