const CLICK_X_OFFSET = 30;
const CLICK_Y_OFFSET = 50;
const RANDOM_CLICK_ROTATION_DEGREE = 90;
const RANDOM_OFFSET_X = 30;

export { CLICK_X_OFFSET, CLICK_Y_OFFSET, RANDOM_CLICK_ROTATION_DEGREE, RANDOM_OFFSET_X };
